// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailStoreLab3.Data;

#nullable disable

namespace RetailStoreLab3.Migrations
{
    [DbContext(typeof(RetailContext))]
    [Migration("20250706054942_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("RetailStoreLab3.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Laptop",
                            Price = 70000m
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Keyboard",
                            Price = 1500m
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Mouse",
                            Price = 500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
