// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailStoreLab7.Data;

#nullable disable

namespace RetailStoreLab7.Migrations
{
    [DbContext(typeof(RetailContext))]
    [Migration("20250706064313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("RetailStoreLab7.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Monitor",
                            Price = 12000m
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Printer",
                            Price = 8000m
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Speakers",
                            Price = 3000m
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Mouse",
                            Price = 900m
                        },
                        new
                        {
                            ProductId = 5,
                            Name = "Keyboard",
                            Price = 1500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
